name: 🧠 Manual CodexDaemon Command

on:
  workflow_dispatch:
    inputs:
      instruction:
        description: "Enter a CodexDaemon instruction"
        required: true
        default: "add a fun fact to README.md"

jobs:
  run-codex:
    runs-on: ubuntu-latest

    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v4

      - name: 🧰 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 🧱 Install dependencies
        run: |
          pip install -r requirements.txt

      - name: 🚀 Run CodexDaemon instruction
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          CODEX_MODEL: ${{ secrets.CODEX_MODEL }}
        run: |
          python3 codex_runner.py "${{ github.event.inputs.instruction }}" --commit

      - name: 📤 Push result
        run: |
          git config user.name "CodexDaemon Bot"
          git config user.email "bot@codexdaemon.local"
          git add .
          git commit -m "🤖 CodexDaemon manual update" || echo "No changes to commit"
          git push
