name: 🧠 CodexDaemon Auto-Review

on:
  push:
    branches: [ main ]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v4

      - name: 🧰 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 🧱 Install dependencies
        run: pip install -r requirements.txt

      - name: 🤖 Run CodexDaemon review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python3 codex_runner.py "analyze codex_runner.py and suggest clarity improvements" --commit

      - name: 📤 Push review results
        run: |
          git config user.name "CodexDaemon Bot"
          git config user.email "bot@codexdaemon.local"
          git add .
          git commit -m "🤖 CodexDaemon auto-review" || echo "No changes to commit"
          git push
