name: 🧠 CodexDaemon Auto-Review

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # allow manual trigger too

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v4

      - name: 🧰 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 🧱 Install dependencies
        run: |
          pip install -r requirements.txt
          pip install openai gitpython python-dotenv rich

      - name: 🚀 Run CodexDaemon Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          CODEX_MODEL: ${{ secrets.CODEX_MODEL }}
        run: |
          echo "Running CodexDaemon self-analysis..."
          python3 codex_runner.py "analyze codex_runner.py and suggest clarity improvements" --commit

      - name: 📤 Push review results
        run: |
          git config user.name "CodexDaemon Bot"
          git config user.email "bot@codexdaemon.local"
          git add .
          git commit -m "🤖 CodexDaemon auto-review" || echo "No changes to commit"
          git push origin main || echo "Push skipped"
